GET http://localhost:3000

### Show All Students

GET http://localhost:3000/students

### Show Student

GET http://localhost:3000/students/2

### Create Student

POST http://localhost:3000/students
Content-Type: application/json

{
    "name": "Blind Adam",
    "gender": "m",
    "course_id": 1
}